# Generated by Django 5.2.4 on 2025-09-19 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_for', models.CharField(choices=[('self', 'Myself'), ('son', 'My Son'), ('daughter', 'My Daughter'), ('brother', 'My Brother'), ('sister', 'My Sister'), ('relative', 'Relative/Friend')], default='self', max_length=20)),
                ('relation_to_profile', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('siblings', models.CharField(blank=True, max_length=10, null=True)),
                ('family_type', models.CharField(blank=True, choices=[('nuclear', 'Nuclear Family'), ('joint', 'Joint Family')], max_length=20, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('looking_for', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_image_privacy', models.CharField(choices=[('public', 'Public'), ('matches', 'Matches Only')], default='public', max_length=20)),
                ('additional_images_privacy', models.CharField(choices=[('public', 'Public'), ('matches', 'Matches Only')], default='matches', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='additional_images/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='api.profile')),
            ],
        ),
    ]
