# Generated by Django 5.2.4 on 2025-09-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_blood_group_profile_facebook_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='verification_documents/'),
        ),
    ]
