# Generated by Django 5.2.4 on 2025-09-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_is_verified_profile_verification_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='document_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
