# Generated by Django 5.2.4 on 2025-09-21 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_convert_height_to_cm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='max_height',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='min_height',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='consent',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lifestyle_habits',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='relation_to_profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tos_accepted',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification_document',
        ),
        migrations.AddField(
            model_name='education',
            name='graduation_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='countries_whitelist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='preference',
            name='marital_statuses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='preference',
            name='max_height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='min_height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='religions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='preference',
            name='require_non_alcoholic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preference',
            name='require_non_smoker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preference',
            name='required_immigration',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('occasionally', 'Occasionally'), ('socially', 'Socially')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='centimeters', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoking',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('occasionally', 'Occasionally'), ('yes', 'Yes')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userlanguage',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('native', 'Native')], default='native', max_length=10),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='preference',
            name='is_hard_filter',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('never_married', 'Never Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='origin_country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('islam', 'Islam'), ('christianity', 'Christianity'), ('hinduism', 'Hinduism'), ('buddhism', 'Buddhism'), ('judaism', 'Judaism'), ('other', 'Other'), ('none', 'None')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='siblings',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='userlanguage',
            unique_together={('profile', 'language')},
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['current_country', 'current_city'], name='api_profile_current_351c54_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['marital_status', 'religion'], name='api_profile_marital_7f240f_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['birth_year'], name='api_profile_birth_y_a7a1da_idx'),
        ),
    ]
