# Generated by Django 5.2.4 on 2025-11-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='countries_whitelist',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='is_hard_filter',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='max_height_cm',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='religions',
        ),
        migrations.AddField(
            model_name='preference',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='religion',
            field=models.CharField(blank=True, choices=[('muslim', 'Muslim'), ('hindu', 'Hindu'), ('christian', 'Christian')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('muslim', 'Muslim'), ('hindu', 'Hindu'), ('christian', 'Christian')], max_length=20, null=True),
        ),
    ]
