# Generated by Django 5.2.4 on 2025-11-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_preference_countries_whitelist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='required_immigration',
        ),
    ]
