# Generated by Django 5.2.4 on 2025-11-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_preference_required_immigration'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='currently_working',
            field=models.BooleanField(default=False),
        ),
    ]
