# Generated by Django 5.2.4 on 2025-11-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_profile_languages_alter_profile_hobbies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='languages',
        ),
    ]
