# Generated by Django 5.0.4 on 2025-11-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_profile_hobbies_remove_profile_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='marital_statuses',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
