# Generated by Django 5.0.4 on 2025-11-10 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_preference_marital_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(storage='api.storage.SupabaseStorage', upload_to='additional_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage='api.storage.SupabaseStorage', upload_to='profile_images/'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(help_text="A short phrase describing the action (e.g., 'viewed your profile').", max_length=255)),
                ('unread', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_profile', models.ForeignKey(help_text='The profile of the user who performed the action.', on_delete=django.db.models.deletion.CASCADE, related_name='initiated_notifications', to='api.profile')),
                ('recipient', models.ForeignKey(help_text='The user who should receive this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('target_profile', models.ForeignKey(blank=True, help_text='Optional: The profile that was the object of the action.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_about_this_profile', to='api.profile')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'unread'], name='api_notific_recipie_563460_idx')],
            },
        ),
    ]
