# Generated by Django 5.0.4 on 2025-11-25 05:48

import api.storage
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_additionalimage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalimage',
            options={'ordering': ['order', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='additionalimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Optional photo caption', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='additionalimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display order in gallery (lower = first)'),
        ),
        migrations.AddField(
            model_name='additionalimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(storage=api.storage.SupabaseStorage(), upload_to='additional_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=api.storage.SupabaseStorage(), upload_to='profile_images/'),
        ),
    ]
