# Generated by Django 5.0.4 on 2025-11-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_additionalimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='faith_tags',
            field=models.JSONField(blank=True, default=list, help_text="User's faith and lifestyle tags", null=True),
        ),
    ]
