# Generated by Django 5.0.4 on 2025-11-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_profile_faith_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='height_cm',
        ),
        migrations.AddField(
            model_name='profile',
            name='height_inches',
            field=models.PositiveSmallIntegerField(blank=True, help_text='height in inches', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skin_complexion',
            field=models.CharField(blank=True, choices=[('fair', 'Fair'), ('light', 'Light'), ('medium', 'Medium'), ('olive', 'Olive'), ('brown', 'Brown'), ('dark', 'Dark')], max_length=20, null=True),
        ),
    ]
