# Generated by Django 5.0.4 on 2025-11-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_profile_height_cm_profile_height_inches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='alcohol',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='smoking',
        ),
    ]
