# Generated by Django 5.0.4 on 2025-11-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_profile_alcohol_remove_profile_smoking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='min_height_cm',
            new_name='min_height_inches',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='require_non_alcoholic',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='require_non_smoker',
        ),
    ]
