# Generated by Django 5.0.4 on 2025-11-30 06:05

import api.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_min_height_cm_preference_min_height_inches_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_image', models.ImageField(help_text='Verification document image (passport, NID, etc.)', storage=api.storage.SupabaseStorage(), upload_to='verification_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes or rejection reason', null=True)),
                ('profile', models.ForeignKey(help_text='Profile that this verification document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='api.profile')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin user who reviewed this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Document',
                'verbose_name_plural': 'Verification Documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['profile', 'status'], name='api_verific_profile_5a0d9c_idx')],
            },
        ),
    ]
