# Generated by Django 5.0.4 on 2025-11-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_verificationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='maternal_family_details',
            field=models.TextField(blank=True, help_text="Uncles, Aunts, Grandparents from Mother's side", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='paternal_family_details',
            field=models.TextField(blank=True, help_text="Uncles, Aunts, Grandparents from Father's side", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='siblings_details',
            field=models.TextField(blank=True, help_text='Details about siblings', null=True),
        ),
    ]
