# Generated by Django 5.0.4 on 2025-11-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_profile_maternal_family_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_on_map',
            field=models.BooleanField(default=True, help_text='Show profile on global map'),
        ),
    ]
