# Generated by Django 5.0.4 on 2025-12-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_profile_show_on_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='show_on_map',
            field=models.BooleanField(default=True, help_text='Show profile on the global map'),
        ),
    ]
