# Generated by Django 5.0.4 on 2025-12-07 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_profile_show_on_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('interests_received', models.PositiveIntegerField(default=0)),
                ('interests_sent', models.PositiveIntegerField(default=0)),
                ('profile_strength', models.PositiveSmallIntegerField(default=0, help_text='Score 0-100')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='api.profile')),
            ],
            options={
                'verbose_name': 'Analytics Snapshot',
                'verbose_name_plural': 'Analytics Snapshots',
                'ordering': ['-date'],
                'unique_together': {('profile', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, help_text='How they found the profile: search, recommendation, profile_list, etc.', max_length=50, null=True)),
                ('viewed_profile', models.ForeignKey(help_text='Profile that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='views_received', to='api.profile')),
                ('viewer', models.ForeignKey(help_text='User who viewed the profile', on_delete=django.db.models.deletion.CASCADE, related_name='views_made', to='api.profile')),
            ],
            options={
                'verbose_name': 'Profile View',
                'verbose_name_plural': 'Profile Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['viewed_profile', 'viewed_at'], name='api_profile_viewed__196e3e_idx'), models.Index(fields=['viewer', 'viewed_at'], name='api_profile_viewer__e08d42_idx')],
            },
        ),
    ]
