# Generated by Django 5.0.4 on 2025-12-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_analyticssnapshot_profileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
