# Generated by Django 5.0.4 on 2025-12-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_profile_is_premium_profile_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='location_preference',
            field=models.CharField(blank=True, choices=[('near_me', 'Near me'), ('abroad', 'Abroad'), ('any', 'Any')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='looking_for_gender',
            field=models.CharField(blank=True, choices=[('bride', 'Bride'), ('groom', 'Groom'), ('any', 'Any')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='min_education',
            field=models.CharField(blank=True, choices=[('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'PhD'), ('any', 'Any')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='partner_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='preferred_professions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lifestyle_priority',
            field=models.CharField(blank=True, choices=[('liberal', 'Liberal'), ('moderate', 'Moderate'), ('conservative', 'Conservative'), ('strictly_religious', 'Strictly Religious')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='willing_to_relocate',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('it_depends', 'It Depends')], max_length=20, null=True),
        ),
    ]
