# Generated by Django 5.0.4 on 2025-12-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_preference_location_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='partner_description',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preferred_professions',
        ),
    ]
