# Generated by Django 5.0.4 on 2025-12-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_preference_partner_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='profession',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
