# Generated by Django 5.0.4 on 2026-01-12 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_messaging_system'),
        ('subscription', '0003_alter_transaction_purpose'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatroom',
            new_name='api_chatroo_partici_b29b42_idx',
            old_name='chatroom_participants_idx',
        ),
        migrations.RenameIndex(
            model_name='chatunlock',
            new_name='api_chatunl_refund__55cb4c_idx',
            old_name='chatunlock_refund_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='api_message_chat_ro_6cbaee_idx',
            old_name='message_room_time_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='api_message_receive_efffdf_idx',
            old_name='message_unread_idx',
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='value',
            field=models.JSONField(help_text='Configuration value (can be string, number, object, etc.)'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='participant_1',
            field=models.ForeignKey(help_text='First participant in the chat', on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_p1', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='participant_2',
            field=models.ForeignKey(help_text='Second participant in the chat', on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_p2', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='chatunlock',
            name='refund_eligible_at',
            field=models.DateTimeField(blank=True, help_text='When this unlock became eligible for refund', null=True),
        ),
        migrations.AlterField(
            model_name='chatunlock',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, help_text='When the refund was processed (credits returned)', null=True),
        ),
        migrations.AlterField(
            model_name='chatunlock',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Transaction record for this unlock payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_unlock', to='subscription.transaction'),
        ),
        migrations.AlterModelTable(
            name='appconfig',
            table=None,
        ),
        migrations.AlterModelTable(
            name='chatroom',
            table=None,
        ),
        migrations.AlterModelTable(
            name='chatunlock',
            table=None,
        ),
        migrations.AlterModelTable(
            name='message',
            table=None,
        ),
    ]
