# Generated by Django 5.0.4 on 2026-01-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_rename_chatroom_participants_idx_api_chatroo_partici_b29b42_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_activated',
            field=models.BooleanField(default=False, help_text='User has paid the activation fee'),
        ),
    ]
