# Generated by Django 5.0.4 on 2026-01-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_profile_is_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_room',
        ),
        migrations.RemoveField(
            model_name='chatunlock',
            name='chat_room',
        ),
        migrations.RemoveField(
            model_name='chatunlock',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='chatunlock',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='ChatUnlock',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
