# Generated by Django 4.2.7 on 2026-01-18 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_message_chat_room_remove_chatunlock_chat_room_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            # Drop the column (if it exists as JSON) and recreate it as VARCHAR(2)
            # or simply ALTER TYPE using NULL to discard potential incompatible JSON data
            sql="""
            ALTER TABLE api_preference 
            ALTER COLUMN country TYPE varchar(2) USING NULL;
            """,
            reverse_sql="""
            ALTER TABLE api_preference 
            ALTER COLUMN country TYPE jsonb USING to_jsonb(country);
            """
        ),
    ]
