# Generated by Django 5.0.4 on 2026-01-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_fix_preference_country_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchunlock',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='matchunlock',
            name='target_profile',
        ),
        migrations.RemoveField(
            model_name='matchunlock',
            name='user',
        ),
        migrations.AddField(
            model_name='interest',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='refund_status',
            field=models.CharField(choices=[('none', 'No Refund'), ('eligible', 'Refund Eligible'), ('processed', 'Refund Processed')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='interest',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='sent', max_length=10),
        ),
        migrations.AddIndex(
            model_name='interest',
            index=models.Index(fields=['status', 'created_at'], name='api_interes_status_db079a_idx'),
        ),
        migrations.AddIndex(
            model_name='interest',
            index=models.Index(fields=['refund_status'], name='api_interes_refund__9a139f_idx'),
        ),
        migrations.DeleteModel(
            name='MatchUnlock',
        ),
    ]
