# Generated by Django 5.0.4 on 2026-01-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_matchunlock_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='share_type',
            field=models.CharField(choices=[('none', 'None'), ('bio_only', 'Bio Data Only'), ('full', 'Full Bio Data (with Image)')], default='none', max_length=20),
        ),
    ]
