# Generated by Django 5.0.4 on 2026-01-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_interest_share_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='origin_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
