# Generated by Django 5.0.4 on 2026-01-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_profile_current_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
