# Generated by Django 5.0.4 on 2026-01-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_preference_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='country',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
