# Generated by Django 5.0.4 on 2026-01-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_emailverification_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='User has completed the onboarding flow'),
        ),
    ]
