"""
Django settings for life_time project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-naq7tg)x(o8xd+^d3f8qr=p^l*%n1t)w4@svcbb+&f1hyq58__'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'RENDER' not in os.environ

if not DEBUG:
    DATABASE_PASSWORD = os.environ.get('DATABASE_PASSWORD')
    if not DATABASE_PASSWORD:
        raise ValueError("DATABASE_PASSWORD environment variable not set in production")
else:
    DATABASE_PASSWORD = os.environ.get('DATABASE_PASSWORD')



ALLOWED_HOSTS = [
    "life-time-pxjp.onrender.com",   # backend Render domain
    "life-time-2jnrxe9xm-s-chys-projects.vercel.app",  # frontend Vercel domain
    "localhost",
    "127.0.0.1"
]

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


CORS_ALLOWED_ORIGINS = [
    "https://life-time-2jnrxe9xm-s-chys-projects.vercel.app",
    "https://life-time-kohl.vercel.app",  # New Vercel frontend domain
    "http://localhost:3000",
]
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cache-control',
]
CSRF_TRUSTED_ORIGINS = [
    "https://life-time-2jnrxe9xm-s-chys-projects.vercel.app",
    "https://life-time-kohl.vercel.app",
    "https://life-time-pxjp.onrender.com",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.apps.ApiConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'storages',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'life_time.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'life_time.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',  # Supabase default
        'USER': 'postgres.airogkqmcjqvvipdwnwh',
        'HOST': 'aws-1-ap-southeast-2.pooler.supabase.com',  # Supabase session pooler host
        'PORT': '5432',
        'PASSWORD': DATABASE_PASSWORD,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_ROOT = BASE_DIR / "staticfiles"


# Tell Django to serve static files using WhiteNoise
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATICFILES_DIRS = []

SUPABASE_JWT_SECRET = 'ZSSOtSBi5+eZ0hS8RkF1AcjgfaX+Srnt1v7KWR4g/+FkBLB360vfTr2XUuFFwWMCqOuQjUshOGLAtHReXVVUeA=='
SUPABASE_AUDIENCE = 'authenticated'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.SupabaseAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# Supabase Storage Configuration for Media Files
if not DEBUG:
    SUPABASE_ACCESS_KEY = os.environ.get('SUPABASE_ACCESS_KEY')
    SUPABASE_SECRET_KEY = os.environ.get('SUPABASE_SECRET_KEY')
    SUPABASE_BUCKET_NAME = os.environ.get('SUPABASE_BUCKET_NAME')
    SUPABASE_PROJECT_ID = os.environ.get('SUPABASE_PROJECT_ID')
    # SUPABASE_ENDPOINT_URL is now derived from SUPABASE_PROJECT_ID if available

    if SUPABASE_PROJECT_ID:
        SUPABASE_ENDPOINT_URL = f"https://{SUPABASE_PROJECT_ID}.supabase.co/storage/v1/s3"
    else:
        # Fallback to direct SUPABASE_ENDPOINT_URL if project ID is not set
        SUPABASE_ENDPOINT_URL = os.environ.get('SUPABASE_ENDPOINT_URL')

    if SUPABASE_BUCKET_NAME:
        DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
        AWS_ACCESS_KEY_ID = SUPABASE_ACCESS_KEY
        AWS_SECRET_ACCESS_KEY = SUPABASE_SECRET_KEY
        AWS_STORAGE_BUCKET_NAME = SUPABASE_BUCKET_NAME
        AWS_S3_ENDPOINT_URL = SUPABASE_ENDPOINT_URL # This is for boto3 to connect
        AWS_S3_REGION_NAME = 'ap-southeast-2' # Explicitly set the region
        AWS_S3_FILE_OVERWRITE = False
        AWS_DEFAULT_ACL = None # It's more secure to use bucket policies

        # Use AWS_S3_CUSTOM_DOMAIN for MEDIA_URL to ensure correct public URLs
        if SUPABASE_PROJECT_ID and SUPABASE_BUCKET_NAME:
            AWS_S3_CUSTOM_DOMAIN = f'{SUPABASE_PROJECT_ID}.supabase.co/storage/v1/object/public/{SUPABASE_BUCKET_NAME}'
            MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
        else:
            # Fallback if custom domain cannot be constructed
            MEDIA_URL = '/media/' # This will likely not work for S3, but prevents crash

        # Ensure all required Supabase variables are set
        required_supabase_vars = {
            'SUPABASE_ACCESS_KEY': SUPABASE_ACCESS_KEY,
            'SUPABASE_SECRET_KEY': SUPABASE_SECRET_KEY,
            'SUPABASE_BUCKET_NAME': SUPABASE_BUCKET_NAME,
            'SUPABASE_PROJECT_ID': SUPABASE_PROJECT_ID, # Now required
            'SUPABASE_ENDPOINT_URL': SUPABASE_ENDPOINT_URL # Derived or set
        }
        missing_vars = [key for key, value in required_supabase_vars.items() if not value]
        if missing_vars:
            raise ValueError(f"Missing Supabase Storage environment variables: {', '.join(missing_vars)}")

# Temporary Logging Configuration for Production Debugging
# This will output detailed logs to the console (Render logs) when DEBUG is False.
# REMEMBER TO REMOVE THIS AFTER DEBUGGING!
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose' if not DEBUG else 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO', # Keep Django's general logs at INFO
            'propagate': False,
        },
        'api': { # Your app's logger
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'storages': { # django-storages logger
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'boto3': { # AWS SDK logger (used by django-storages)
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'botocore': { # AWS SDK logger (used by django-storages)
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING', # Default level for anything not explicitly set
    }
}

if not DEBUG:
    # Only apply this logging configuration in production
    # This ensures that debug logs are sent to the console (Render logs)
    # when DEBUG is False.
    # You might want to adjust levels or remove this block after debugging.
    LOGGING['loggers']['django']['level'] = 'DEBUG'
    LOGGING['loggers']['api']['level'] = 'DEBUG'
    LOGGING['loggers']['storages']['level'] = 'DEBUG'
    LOGGING['loggers']['boto3']['level'] = 'DEBUG'
    LOGGING['loggers']['botocore']['level'] = 'DEBUG'


