"""
Django settings for life_time project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv  # Import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))  # Load .env from backend directory


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 'django-insecure-naq7tg)x(o8xd+^d3f8qr=p^l*%n1t)w4@svcbb+&f1hyq58__')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'RENDER' not in os.environ

if not DEBUG:
    DATABASE_PASSWORD = os.environ.get('DATABASE_PASSWORD')
    if not DATABASE_PASSWORD:
        raise ValueError(
            "DATABASE_PASSWORD environment variable not set in production")
else:
    DATABASE_PASSWORD = os.environ.get('DATABASE_PASSWORD')


ALLOWED_HOSTS = [
    "life-time-pxjp.onrender.com",   # backend Render domain
    "life-time-2jnrxe9xm-s-chys-projects.vercel.app",  # frontend Vercel domain
    "localhost",
    "127.0.0.1"
]

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


CORS_ALLOWED_ORIGINS = [
    "https://life-time-2jnrxe9xm-s-chys-projects.vercel.app",
    "https://life-time-kohl.vercel.app",  # New Vercel frontend domain
    "http://localhost:3000",
]
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cache-control',
]
CSRF_TRUSTED_ORIGINS = [
    "https://life-time-2jnrxe9xm-s-chys-projects.vercel.app",
    "https://life-time-kohl.vercel.app",
    "https://life-time-pxjp.onrender.com",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.apps.ApiConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'storages',
]

# Add Django Debug Toolbar only if installed
if DEBUG:
    try:
        import debug_toolbar
        INSTALLED_APPS.append('debug_toolbar')
    except ImportError:
        pass


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Add Django Debug Toolbar middleware only if installed
if DEBUG:
    try:
        import debug_toolbar
        MIDDLEWARE.insert(3, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    except ImportError:
        pass


ROOT_URLCONF = 'life_time.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'life_time.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',  # Supabase default
        'USER': 'postgres.airogkqmcjqvvipdwnwh',
        'HOST': 'aws-1-ap-southeast-2.pooler.supabase.com',  # Supabase session pooler host
        'PORT': '5432',
        'PASSWORD': DATABASE_PASSWORD,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_ROOT = BASE_DIR / "staticfiles"


# Tell Django to serve static files using WhiteNoise
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATICFILES_DIRS = []

SUPABASE_JWT_SECRET = os.environ.get('SUPABASE_JWT_SECRET')
SUPABASE_AUDIENCE = 'authenticated'

if not DEBUG and not SUPABASE_JWT_SECRET:
    raise ValueError(
        "SUPABASE_JWT_SECRET environment variable not set in production")

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.SupabaseAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# Supabase Storage Configuration for Media Files
# Removed django-storages configuration as we are switching to the official Supabase Python client.

# Supabase Storage Configuration for Media Files
# Using the official Supabase Python client.
SUPABASE_URL = os.environ.get("SUPABASE_URL")
# Use service_role key for backend operations
SUPABASE_KEY = os.environ.get("SUPABASE_KEY")
SUPABASE_BUCKET_NAME = os.environ.get("SUPABASE_BUCKET_NAME")

if not DEBUG:
    if not SUPABASE_URL:
        raise ValueError(
            "SUPABASE_URL environment variable not set in production")
    if not SUPABASE_KEY:
        raise ValueError(
            "SUPABASE_KEY environment variable not set in production")
    if not SUPABASE_BUCKET_NAME:
        raise ValueError(
            "SUPABASE_BUCKET_NAME environment variable not set in production")

# Set the custom storage backend
DEFAULT_FILE_STORAGE = 'api.storage.SupabaseStorage'

# MEDIA_URL for public access to Supabase-stored files
if SUPABASE_URL and SUPABASE_BUCKET_NAME:
    # Construct the public URL base for the bucket
    # Example: https://<project_id>.supabase.co/storage/v1/object/public/<bucket_name>/
    # We need to extract project_id from SUPABASE_URL if it's not explicitly set
    project_id = SUPABASE_URL.split(
        '//')[1].split('.')[0] if SUPABASE_URL else None
    if project_id:
        MEDIA_URL = f'https://{project_id}.supabase.co/storage/v1/object/public/{SUPABASE_BUCKET_NAME}/'
    else:
        MEDIA_URL = '/media/'  # Fallback, though this should be caught by SUPABASE_URL check
else:
    MEDIA_URL = '/media/'  # Fallback for local development or if variables are missing

# Django Debug Toolbar Configuration (Development Only)
if DEBUG:
    INTERNAL_IPS = [
        '127.0.0.1',
        'localhost',
    ]

# Reverted temporary logging configuration.
