# Generated by Django 5.0.4 on 2026-01-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscriptionplan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('credit_topup', 'Credit Top-up'), ('chat_unlock', 'Chat Unlock')], max_length=20),
        ),
    ]
