# Generated by Django 5.0.4 on 2026-01-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_transaction_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
