# Generated by Django 5.0.4 on 2026-01-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_transaction_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price_usd',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='base_currency',
            field=models.CharField(default='BDT', max_length=3),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_bdt',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in BDT (Base Currency)', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='credit_amount',
            field=models.PositiveIntegerField(default=0, help_text='Credits given (for bundles)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=0, help_text='Duration in days. 0 for permanent.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(choices=[('subscription', 'Subscription (Legacy)'), ('profile_activation', 'Profile Activation'), ('credit_topup', 'Credit Top-up'), ('chat_unlock', 'Chat Unlock')], max_length=20),
        ),
    ]
